SELECT JOB
FROM JOBS

SELECT NAME, BDATE
FROM PERSONS

SELECT PERCENT, RELIGION, COUNTRY
FROM RELIGIONS

SELECT COUNTRY, POP, AREA, GNP,
LANGUAGE, LITERACY, COUNTRY
FROM COUNTRIES

SELECT *, COUNTRY
FROM COUNTRIES